---
 #- hosts: nginx
 #- name: nginx assignment
 #  import_playbook: ../static-assignments/nginx.yml

 #- hosts: db
 #- name: database assignment
 #  import_playbook: ../static-assignments/database.yml

 #- hosts: artifactory
 #- name: artifactory assignment
 # ansible.builtin.import_playbook: ../static-assignments/artifactory.yml

#- hosts: todo
#- name: Deploy the todo application
 # import_playbook: ../static-assignments/deployment.yml


- hosts: sonar
- name: sonar assignment
  ansible.builtin.import_playbook: ../static-assignments/sonar.yml


#- name: import common file
# import_playbook: ../static-assignments/common.yml
#  tags:
#  - always

#- name: include env-vars file
# import_playbook: ../dynamic-assignments/env-vars.yml 

#- name: webserver assignment
#  import_playbook: ../static-assignments/webservers.yml

#- name: Loadbalancers assignment
# import_playbook: ../static-assignments/loadbalancers.yml
# when: load_balancer_is_required

#- name: import database file
#  import_playbook: ../static-assignments/db.yml
  




